---
title: "Fashion MNIST"
output: Fashion MNIST
---

```{r}
  load_image_file <- function(filename) {
    ret = list()
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    ret$n = readBin(f,'integer',n=1,size=4,endian='big')
    nrow = readBin(f,'integer',n=1,size=4,endian='big')
    ncol = readBin(f,'integer',n=1,size=4,endian='big')
    x = readBin(f,'integer',n=ret$n*nrow*ncol,size=1,signed=F)
    ret$x = matrix(x, ncol=nrow*ncol, byrow=T)
    close(f)
    ret
  }
  load_label_file <- function(filename) {
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    n = readBin(f,'integer',n=1,size=4,endian='big')
    y = readBin(f,'integer',n=n,size=1,signed=F)
    close(f)
    y
  }
  train <- load_image_file('~/OneDrive/ML/ml-private/fashion-mnist/train-images-idx3-ubyte')
  test <- load_image_file('~/OneDrive/ML/ml-private/fashion-mnist/t10k-images-idx3-ubyte')
  
  train$y <- load_label_file('~/OneDrive/ML/ml-private/fashion-mnist/train-labels-idx1-ubyte')
  test$y <- load_label_file('~/OneDrive/ML/ml-private/fashion-mnist/t10k-labels-idx1-ubyte')


show_digit <- function(arr784, col=gray(12:1/12), ...) {
  image(matrix(arr784, nrow=28)[,28:1], col=col, ...)
}

```

```{r}
train$x <- train$x / 255
test$x <- test$x / 255

train$y <- to_categorical(train$y)
test$y <- to_categorical(test$y)

validation <- list()
validation_indices <- sample(1:60000, size = 10000)
validation$x <- train$x[validation_indices,]
train$x <- train$x[-validation_indices,]

validation$y <- train$y[validation_indices,]
train$y <- train$y[-validation_indices,]

train$x <- array_reshape(train$x, c(50000, 28, 28, 1))
test$x <- array_reshape(test$x, c(10000, 28, 28, 1))
validation$x <- array_reshape(validation$x, c(10000, 28, 28, 1))

```


```{r}
model <- keras_model_sequential() %>%
  layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = "relu", input_shape = c(28, 28, 1)) %>%
  layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = "relu") %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  layer_dropout(rate = 0.2) %>%
  layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = "relu") %>%
  layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = "relu") %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  layer_dropout(rate = 0.3) %>%
  layer_conv_2d(filters = 128, kernel_size = c(3,3), activation = "relu") %>%
  layer_flatten() %>%
  layer_dense(units = 256, activation = "relu", kernel_regularizer = regularizer_l2(0.001)) %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 64, activation = "relu", kernel_regularizer = regularizer_l2(0.001)) %>%
  layer_dense(units = 10, activation = "softmax")

summary(model)

model %>% compile(loss = "categorical_crossentropy", optimizer = optimizer_rmsprop(lr = 0.001), metrics = c("acc"))

history <- model %>% fit(train$x, train$y, epochs = 50, batch_size = 128, validation_data = list(validation$x, validation$y))
  
```

```{r}

plot(history)

test$x <- array_reshape(test$x, c(10000, 28, 28, 1))
results <- model %>% evaluate(test$x, test$y)

model %>% save_model_hdf5("~/OneDrive/ML/ml-private/fashion-mnist/fashion_model_5.h5")


```



